### ISSUE TITLE
Please give an update of the package list to install

### ISSUE THREAD

**Issue by nbauma109** [orphan-oss/launch4j-maven-plugin#167]
The library name pattern with "32" in it is an old pattern that is not supported anymore. But even after renaming and adding support for i386, I'm still getting the issue:

        sudo dpkg --add-architecture i386
        sudo apt-get -y update
        sudo apt-get -y install libz1:i386 libncurses5:i386 libbz2-1.0:i386

Cannot run program "/root/.m2/repository/net/sf/launch4j/launch4j/3.14/launch4j-3.14-workdir-linux64/bin/windres": error=2, No such file or directory -> [Help 1]

Before that it says:

[INFO] [INFO] launch4j: Compiling resources
[INFO] [INFO] launch4j: Generated resource file...

Normal execution path is:

[INFO] [INFO] launch4j: Compiling resources
[INFO] [INFO] launch4j: Linking
[INFO] [INFO] launch4j: Wrapping

_Originally posted by @nbauma109 in https://github.com/lukaszlenart/launch4j-maven-plugin/issues/4#issuecomment-1032280318_

Also tried to follow the FAQ:

lib32z1
lib32ncurses5
lib32bz2-1.0 (has been ia32-libs in older Ubuntu versions)
zlib.i686
ncurses-libs.i686
bzip2-libs.i686

The last 3 libs would not install. They seem to be for CentOS (https://github.com/lukaszlenart/launch4j-maven-plugin/issues/4#issuecomment-63477533)
I'm using Ubuntu 20.

**Comment by lukaszlenart** [comment]
Did you try to install any of these?

https://packages.ubuntu.com/search?keywords=lib32z1
https://packages.ubuntu.com/search?keywords=lib32ncurses
https://packages.ubuntu.com/search?keywords=libbz2

**Comment by nbauma109** [comment]
Yes except the dev suffixed and the ocaml ones

**Comment by lukaszlenart** [comment]
But did you install `lib32ncurses6`? `lib32ncurses5` is not available for Ubuntu 20.x

**Comment by lukaszlenart** [comment]
To be honest I have no idea how can I help you, this is Launch4j internal tool and it's not part of the Maven Plugin. 

I just used docker to run Ubuntu 20.x and downloaded the jar 
```
wget https://repo1.maven.org/maven2/net/sf/launch4j/launch4j/3.14/launch4j-3.14-workdir-linux64.jar
```

then extracted it

```
jar xf launch4j-3.14-workdir-linux64.jar
```

entered the folder
```
cd ./launch4j-3.14-workdir-linux64/bin
```

added `execute` permission
```
chmod +x windres
```

and started the tool
```
./windres --help
```

everything looks good, not sure if this is a proper way of checking missing libraries, but the only I have.

Do you have a Maven project which I can test?

**Comment by nbauma109** [comment]
I know more about the issue now : it only happens when launch4j maven plugin is used together with qcastel/github-actions-maven-release@master.
Maven build is here: https://github.com/nbauma109/jd-gui-duo/actions/runs/1819604565

**Comment by nbauma109** [comment]
I'd say don't spend too much time on this, it looks like an edge case of an edge case
