### ISSUE TITLE
JavaFX example

### ISSUE THREAD

**Issue by johntor** [orphan-oss/launch4j-maven-plugin#184]
Could you please provide a pom.xml example of a Windows JavaFX application for Java11 and beyond versions.

How can I include everything into exe? Is it advisable? 
Currently I use:
`<opt>--module-path %PATH_TO_FX%</opt>` 
but I have to setup %PATH_TO_FX% to every installation which I don't like very much...

Thank you in advance!

J!

**Comment by lukaszlenart** [comment]
Do you use Maven to build your app? Did you add the following dependency:

```xml
<dependency>
  <groupId>org.openjfx</groupId>
  <artifactId>javafx-controls</artifactId>
  <version>18.0.2</version>
</dependency>
```
?

To include everything in the exe you must build [an uber jar](https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html), second option is to have the exe and all the JARs packed into a ZIP file using [the assembly plugin](https://maven.apache.org/plugins/maven-assembly-plugin/). The exe is just a wrapper around the JAR with your app.

**Comment by johntor** [comment]
Thank you very much for your reply!!! (sorry about my late reply)

I tried the 'uber jar' suggestion with success!

Is it advisable to use such a big file?

Thank you once more!

J!

**Comment by lukaszlenart** [comment]
What you mean by big? If this is a problem you can always prepare an assembly as a ZIP file, then use a setup creator which will install and unpack the ZIP -> https://installforge.net/

**Comment by lukaszlenart** [comment]
There is no problem with having an uber jar - all the jars are loaded at once anyway, but JVM's ClassLoader loads just class that are used at the given time.
