### ISSUE TITLE
Plugin causing errors in project reports

### ISSUE THREAD

**Issue by bradleylarrick** [orphan-oss/launch4j-maven-plugin#187]
Running the launch4j-maven-plugin is corrupting the results of the maven-project-info-reports-plugin. The Plugin Management and Plugins reports have all the GroupId, ArtifactId and Version values replaced with the GroupId, ArtifactId and Version of the current project.

A sample project reproducing the problem can be found at https://github.com/bradleylarrick/launch4j-plugin-error.git.

**Comment by bradleylarrick** [comment]
I did some additional testing on this and determined that the problem is caused by the following line in the retrieveBinaryBits() method in Launch4jMojo:

        configuration.setProject(session.getCurrentProject());

Commenting out this line in my environment solved the problem with no apparent side effects.

**Comment by lukaszlenart** [comment]
Thanks for taking a look into that, I wonder how to solve this - maybe a dedicated configuration option to disable such behaviour would be a good idea?

**Comment by bradleylarrick** [comment]
As I mentioned above, commenting out the line that sets the project in the configuration object solved the problem.

**Comment by bradleylarrick** [comment]
BTW: Once I figured out how to properly configure the JRE path, version 2.2.0 works without this problem.

**Comment by lukaszlenart** [comment]
Not sure if I get it, so there is no problem, right? And we can close this issue?

**Comment by bradleylarrick** [comment]
That's correct. The problem appears to be solved in 2.2.  This ticket can be closed.
