### ISSUE TITLE
need a configuration option to skip plugin

### ISSUE THREAD

**Issue by garretwilson** [orphan-oss/launch4j-maven-plugin#189]
It is typical and even expected for Maven plugins to have a `<skip>` option, so that we can provide (via properties, profiles, etc.) a way to skip the plugin execution. See for example the [Antrun Plugin `<skip>` option](https://maven.apache.org/plugins/maven-antrun-plugin/run-mojo.html#skip) and the [Maven Assembly Plugin `<skipAssembly>` option](https://maven.apache.org/plugins/maven-assembly-plugin/single-mojo.html#skipAssembly). (I could provide a long list of similar plugins.)

Please provide a Maven configuration option to skip execution of this plugin.

**Comment by lukaszlenart** [comment]
ver. 2.1.3 is out and under way to the Central

**Comment by garretwilson** [comment]
Thanks for getting to this so quickly. This is awesome!

Now I'll be able to reopen [JAVA-287](https://globalmentor.atlassian.net/browse/JAVA-287) and add the finishing touches to the GlobalMentor root POM. Just by specifying a `exe.main.class` to the POM, an executable JAR and Windows executable will be generated automatically! (I had to pay several tricks to make this happen.) As mentioned in the ticket. Launch4J was the last plugin I was waiting for to have the `<skip>` option to make it work fully automatically. Thank you!

And I was just going to ask about the next release, but you just posted that it's going out. Woohoo! What a positive way to start the day. 🎉

**Comment by garretwilson** [comment]
This is beautiful! I already integrated the new version, and it works great. Thanks again.
