### ISSUE TITLE
Charset problem in exe file description field.

### ISSUE THREAD

**Issue by garretwilson** [orphan-oss/launch4j-maven-plugin#196]
I'm not sure if this problem is in the Launch4J plugin or in Launch4J itself. I opened [Launch4J Bug 221](https://sourceforge.net/p/launch4j/bugs/221/), but no one replied. I would imagine that the problem is within Launch4J itself, as the values start out in the POM, which in XML should be in Unicode anyway. There is a slight possibility of some encoding problem when passing the values to Launch4J, so I thought I'd raise it here as well. If it turns out that you're passing the values unchanged to Launch4J and the issue is instead in Launch4J, feel free to close this issue as invalid.

I'm generating an executable from Maven via the launch4j-maven-plugin. Because my Maven configuration (which gets passed to the Launch4J Maven Plugin) is in XML, I am confident that the source encoding has no problem, as XML ultimately gets parsed as Unicode. My project description is `<description>FooBar™</description>`, and this is used as the Launch4J file description:

```xml
<fileDescription>${project.description}</fileDescription>
```

Unfortunately in the resulting `foobar.exe`, if I right click and look at Details > "File description", it shows `FooBar?`, not `FooBar™`. Apparently the incorrect charset was used in the file. (I don't know what charset a `.exe` file expects for this metadata.)

Note that the copyright symbol `©` shows up fine in the "Copyright" field. This is not surprising as the copyright symbol is U+00A9 (within ISO-8859-1, code page Windows-1252, and even ASCII), while the trademark symbol is U+2122. So the copyright symbol is more lenient, as you could get the charset incorrect and still have the copyright symbol show up as it is the same value in many charsets.

Any idea where this bug is coming from?

**Comment by lukaszlenart** [comment]
Launch4j plugin is a wrapper around the existing `Config` & `Builder` classes from Launch4j, so this is a pure Java to Java "communication" using UTF-8 (all Java sources needs to be encoded with it).

I noticed that internally Launch4j is using `ISO-8859-1` to prepare a resource file used to create exe descriptor and it looks like the ™ is not supported:
https://stackoverflow.com/questions/8207968/how-to-use-trademarktm-in-iso-8859-1-encoding
https://cs.stanford.edu/people/miles/iso8859.html

**Comment by garretwilson** [comment]
> I noticed that internally Launch4j is using `ISO-8859-1` to prepare a resource file used to create exe descriptor and it looks like the ™ is not supported.

Yeah, the `™` character simply doesn't exist in ISO-8859-1, which is only the bottom 256 characters of Unicode. (ASCII is the bottom 128.) I wonder why they are using ISO-8859-1? I wish they would reply to the bug.

Oh well, it was a long shot but I thought I'd check. Thank you for looking into it.
