### ISSUE TITLE
Configuration error in 2.2.0 and 2.3.0

### ISSUE THREAD

**Issue by uwemock** [orphan-oss/launch4j-maven-plugin#212]
I tried to upgrade from 2.1.1 to 2.3.0 and I got this error: "Enter: JRE path"

No hint where to enter the path or what JRE path to enter. Same thing on 2.2.0. Version 2.1.3 works.

**Comment by lukaszlenart** [comment]
Please read [docs](https://launch4j.sourceforge.net/docs.html), you must provide `<jre/>` as it is a required option from Launch4j 3.50, see the example [here](https://github.com/orphan-oss/launch4j-demo/blob/master/pom.xml#L50)
